Repository Misfit-Station/Misfit-Station-14, pull requests merged in 2025-09, with the labels that each got.

#9 chore: RGA and map schema test fail fix
  .github/Schemas/mapfile_requirements.txt
  .github/Schemas/rga.yml
  .github/Schemas/rga_requirements.txt
  .github/Schemas/rga_validators.py
  .github/workflows/validate-rgas.yml
  .github/workflows/validate_mapfiles.yml
Labels: Changes: No C#, size/S

#5 feat: Vulp Ops!
  Resources/Locale/en-US/markings/vulpkanin.ftl
  Resources/Prototypes/Entities/Mobs/Customization/Markings/Vulpkanin/vulpkanin_ears.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/Vulpkanin/vulpkanin_tail.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/scars.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/tattoos.yml
  Resources/Prototypes/Entities/Mobs/Species/vulpkanin.yml
  Resources/Prototypes/Species/vulpkanin.yml
  Resources/Prototypes/Voice/speech_emote_sounds.yml
  Resources/Textures/Mobs/Customization/Vulpkanin/ear_markings.rsi/meta.json
  Resources/Textures/Mobs/Customization/Vulpkanin/ear_markings.rsi/wolf-inner.png
  Resources/Textures/Mobs/Customization/Vulpkanin/ear_markings.rsi/wolf.png
  Resources/Textures/Mobs/Customization/Vulpkanin/head_markings.rsi/meta.json
  Resources/Textures/Mobs/Customization/Vulpkanin/head_markings.rsi/vulpine-lines.png
  Resources/Textures/Mobs/Customization/Vulpkanin/head_markings.rsi/vulpine.png
  Resources/Textures/Mobs/Customization/Vulpkanin/tail_markings.rsi/fox-fade.png
  Resources/Textures/Mobs/Customization/Vulpkanin/tail_markings.rsi/fox-tip.png
  Resources/Textures/Mobs/Customization/Vulpkanin/tail_markings.rsi/fox.png
  Resources/Textures/Mobs/Customization/Vulpkanin/tail_markings.rsi/meta.json
  Resources/Textures/Mobs/Customization/Vulpkanin/tail_markings.rsi/otie.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/full.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/head_f.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/head_m.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/icon.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/l_arm.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/l_foot.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/l_hand.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/l_leg.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/meta.json
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/overlay_husk.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/r_arm.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/r_foot.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/r_hand.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/r_leg.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/torso_f.png
  Resources/Textures/_Misfit/Mobs/Species/Vulpkanin/parts.rsi/torso_m.png
Labels: Changes: Sprites, S: Needs Review, S: Untriaged, Changes: No C#, size/M

#11 feat: add synth trait + refactor
  Content.Server/StationEvents/Events/IonStormRule.cs
  Content.Server/_CD/Traits/SynthComponent.cs
  Content.Server/_CD/Traits/SynthSystem.cs
  Content.Server/_Misfit/Announcements/IonStormNotifierComponent.cs
  Content.Shared/Chat/TypingIndicator/TypingIndicatorComponent.cs
  Resources/Locale/en-US/_CD/reagents/meta/biological.ftl
  Resources/Locale/en-US/_CD/station/events.ftl
  Resources/Locale/en-US/_CD/traits/traits.ftl
  Resources/Prototypes/_CD/Reagents/biological.yml
  Resources/Prototypes/_CD/Traits/traits.yml
Labels: S: Needs Review, S: Untriaged, size/M

#12 feat: add species based trait hiding
  Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
  Content.Shared/Traits/TraitPrototype.cs
Labels: Changes: UI, S: Untriaged, size/S
